main_app/urls.py
from django.urls import path

from . import views

app_name = "main"

urlpatterns = [
    path("", views.home, name="home"),
    path("about/", views.about, name="about"),
    path("pokemon/", views.PokemonList.as_view(), name="pokemon_index"),
    path("pokemon/create/", views.PokemonCreate.as_view(), name="pokemon_create"),
    path("pokemon/<int:pk>/update/", views.PokemonUpdate.as_view(), name="pokemon_update"),
    path("contests/<int:pk>/update/", views.contest_update, name="contest_update"),
    path("pokemon/<int:pk>/delete/", views.PokemonDelete.as_view(), name="pokemon_delete"),
    path("contests/<int:pk>/delete/", views.ContestDelete.as_view(), name="contest_delete"),
    path("pokemon/<int:pk>/", views.detail, name="pokemon_detail"),
    path("pokemon/<int:pk>/training/create", views.add_training, name="training_create"),
    path("contests/", views.ContestIndex.as_view(), name="contests_index"),
    path("contests/create/", views.ContestCreate.as_view(), name="contest_create"),
    path("pokemon/<int:poke_id>/contests/<int:contest_id>/associate", views.assoc_contest, name="assoc_contest"),
    path("pokemon/<int:poke_id>/contests/<int:contest_id>/disassociate", views.disassoc_contest, name="disassoc_contest"),
]

pokecollector/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("main_app.urls")),
]

main_app/models.py
import datetime

from django.contrib.postgres.fields import ArrayField
from django.db import models
from django.urls import reverse

def get_empty_moveset():
    return ["" for i in range(4)]

# Create your models here.
class Pokemon(models.Model):
    number = models.IntegerField()
    nickname = models.CharField(max_length=100)
    level = models.IntegerField()
    moveset = ArrayField(models.CharField(max_length=64, default=str), size=4, default=list)

    def __str__(self):
        return self.nickname

    def get_absolute_url(self):
        return reverse("main:pokemon_detail", kwargs={"pk": self.id})

    def is_energetic(self):
        return len(self.training_set.filter(date=datetime.date.today())) < 3


class Contest(models.Model):
    name = models.CharField(max_length=128, default="no name")
    pokemon = models.ManyToManyField(Pokemon)
    winner = models.ForeignKey(Pokemon, on_delete=models.DO_NOTHING, related_name="+")
    date = models.DateField(default=datetime.date.today)


class Training(models.Model):
    activity = models.CharField(max_length=100, default="")
    exp_points = models.IntegerField(default=0)
    date = models.DateField(default=datetime.date.today)
    pokemon = models.ForeignKey(Pokemon, on_delete=models.CASCADE)

    class Meta:
        ordering = ("-date",)
    def __str__(self):
        return f"{self.activity} at {self.date}"

main_app/forms.py
from django.forms import ModelForm, CharField, ModelMultipleChoiceField, CheckboxSelectMultiple
from django.contrib.postgres.forms import SplitArrayField

from .models import Pokemon, Training, Contest


class PokemonForm(ModelForm):
    moveset = SplitArrayField(CharField(max_length=64), 4, remove_trailing_nulls=True)
    class Meta:
        model = Pokemon
        fields = "__all__"

class TrainingForm(ModelForm):
    class Meta:
        model = Training
        fields = ["activity", "exp_points", "date"]

class ContestForm(ModelForm):
    class Meta:
        model = Contest
        fields = ["name", "date", "winner"]

main_app/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse
from django.views.generic import CreateView, DetailView, ListView, UpdateView, DeleteView

from .forms import PokemonForm, TrainingForm, ContestForm
from .models import Pokemon, Training, Contest


# Create your views here.
def home(request):
    return render(request, "home.html")

def about(request):
    return render(request, "about.html")

def detail(request, pk):
    pokemon = get_object_or_404(Pokemon, id=pk)

    contests_ids = pokemon.contest_set.all().values_list("id")
    contests_non_participant = Contest.objects.exclude(id__in=contests_ids)
    return render(request, "detail.html", {
        "training_form": TrainingForm(),
        "pokemon": pokemon,
        "contests_non_participant": contests_non_participant,
    })


class PokemonCreate(CreateView):
    model = Pokemon
    fields = "__all__"
    success_url = "/pokemon/{id}"

    def get_form_class(self):
        return PokemonForm

class PokemonUpdate(UpdateView):
    model = Pokemon
    fields = ["nickname", "moveset", "level"]
    def get_form_class(self):
        return PokemonForm


class PokemonDelete(DeleteView):
    model = Pokemon
    success_url = "/pokemon/"

def add_training(request, pk):
    form = TrainingForm(request.POST)
    if form.is_valid():
        training = form.save(commit=False)
        training.pokemon_id = pk
        training.save()
    return redirect("main:pokemon_detail", pk=pk)

    

class PokemonList(ListView):
    model = Pokemon
    context_object_name = "pokelist"
    template_name = "pokemon/index.html"

def assoc_contest(request, poke_id, contest_id):
    contest = get_object_or_404(Contest, id=contest_id)
    pokemon = get_object_or_404(Pokemon, id=poke_id)
    contest.pokemon.add(pokemon)
    return redirect("main:pokemon_detail", pk=poke_id)

def disassoc_contest(request, poke_id, contest_id):
    contest = get_object_or_404(Contest, id=contest_id)
    pokemon = get_object_or_404(Pokemon, id=poke_id)
    contest.pokemon.remove(pokemon)
    return redirect("main:pokemon_detail", pk=poke_id)

class ContestCreate(CreateView):
    model = Contest
    success_url = "/contests/"
    def get_form_class(self):
        return ContestForm

class ContestIndex(ListView):
    model = Contest
    template_name = "contest/index.html"
    context_object_name = "contests"

def contest_update(request, pk):
    contest = get_object_or_404(Contest, id=pk)
    print(contest.pokemon.all())
    if request.method == "GET":
        form = ContestForm(instance=contest)

        return render(request, "main_app/contest_form.html", {
            "contest": contest,
            "form": form
        })
    elif request.method == "POST":
        form = ContestForm(request.POST, instance=contest)
        if form.is_valid():
            form.save()
    return redirect("main:contests_index")


class ContestDelete(DeleteView):
    model = Contest

main_app/templates/about.html
{% extends 'base.html' %}
{% block content %}
<section>
    <h1 class="heading-text">About PokéCollector!</h1>
    <p class="text">This is some information about PokéCollector.
        You can show off your collection of Pokémon to the world!
    </p>
</section>

{% endblock %}

main_app/templates/base.html
<!DOCTYPE html>
{% load static %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>PokéCollector</title>
    <link rel="stylesheet" href="{% static 'css/materialize.1.0.0.min.css' %}" />
    <link rel="stylesheet" href="{% static 'css/styles.css' %}" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
</head>
<body>
    <header class="navbar-fixed">
        <nav>
            <div class="nav-wrapper">
                <ul>
                    <li><a href="/" class="left brand-logo">PokéCollector</a></li>
                </ul>
                <ul class="right">
                    <li><a href="{% url 'main:about' %}">About</a></li>
                    <li><a href="{% url 'main:pokemon_index' %}">My Collection</a></li>
                    <li><a href="{% url 'main:contests_index' %}">Contests</a></li>
                </ul>
            </div>
        </nav>
    </header>

    <main class="container">
        {% block content %}
        {% endblock %}
    </main>

    <footer class="page-footer">
        <p class="center-align footer-copyright">Fan website designed by Aaron Ishibashi
    </footer>
</body>
</html>

main_app/templates/contest/index.html
{% extends 'base.html' %}
{% block content %}
    <h1>Contest List</h1>
    <a class="btn" href="{% url 'main:contest_create' %}">Add Contest</a>
    {% for contest in contests %}
        <div class="card">
            <div class="card-content">
                <h4>{{ contest.name }}</h4>
                <p>on {{ contest.date.month }}/{{ contest.date.day }}/{{ contest.date.year }}</p>
                <p>Winner: <span class="teal-text">{{ contest.winner.nickname }}</span></p>
                <p>Contestants:</p>
                <ul>
                    {% for poke in contest.pokemon.all %}
                        <li>- {{ poke.nickname }}</li>
                    {% endfor %}
                </ul>
            </div>
            <div class="card-action">
                <a href="{% url 'main:contest_update' contest.id %}">Edit</a>
                <a href="{% url 'main:contest_delete' contest.id %}">Delete</a>
            </div>
        </div>
    {% empty %}
        <p>No contests to show.</p>
    {% endfor %}
{% endblock %}

main_app/templates/detail.html
{% extends 'base.html' %}
{% block content %}
    <section class="row">
        <section class="col s6">
            {% include 'partials/pokemon-card.html' %}
        </section>
        <section class="col s6">
            <form action="{% url 'main:training_create' pokemon.id %}" method="POST">
                {% csrf_token %}
                {{ training_form.as_p }}
                <input type="submit" value="Add Training" />
            </form>
            <div>
                <div>
                    {% if pokemon.is_energetic %}
                        <p class="teal=text">{{ pokemon.nickname }} is ready for some training!</p>
                    {% else %}
                        <p class="grey-text">{{ pokemon.nickname }} looks tired.</p>
                    {% endif %}
                </div>

                <table>
                    <thead>
                        <tr><th>Training</th><th>Exp</th><th>Date</th></tr>
                    </thead>
                    <tbody>
                        {% for session in pokemon.training_set.all %}
                        <tr>
                            <td>{{session.activity}}</td>
                            <td>{{session.exp_points}}</td>
                            <td>{{session.date}}</td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </section>
    </section>
    <hr />
    <section class="row">
        <h2>Contests</h2>
        <div class="col s6">
            <h4>Participated in</h4>
            {% for contest in pokemon.contest_set.all %}
                <div class="card">
                    <div class="card-content">
                        <h5>{{ contest.name }} <span class="teal-text">{% if contest.winner.id == pokemon.id %}: 1st Place{% endif %}</span></h5>
                        <p>{{ contest.date }}</p>
                    </div>
                    <div class="card-action">
                        <a href="{% url 'main:disassoc_contest' pokemon.id contest.id%}">Remove</a>

                    </div>
                </div>
            {% empty %}
                <p>no contests...</p>
            {% endfor %}
        </div>
        <div class="col s6">
            <h4>Available</h4>
            {% for contest in contests_non_participant %}
                <div class="card">
                    <div class="card-content">
                        <h5>{{ contest.name }}</h5>
                        <p>{{ contest.date }}</p>
                    </div>
                    <div class="card-action">
                        <a href="{% url 'main:assoc_contest' pokemon.id contest.id %}">Add</a>
                    </div>
                </div>
            {% empty %}
                <p>no contests available...</p>
            {% endfor %}
        </div>
    </section>
    <script>
        window.addEventListener("load", () => {
            const dateEl = document.getElementById("id_date");
            M.Datepicker.init(dateEl, {
                format:  "yyyy-mm-dd",
                defaultDate: new Date(),
                setDefaultDate: true,
                autoClose: true,
            });
        });

    </script>
{% endblock %}

main_app/templates/home.html
{% extends 'base.html' %}
{% block content %}
<section>
    <h1 class="heading-text">Welcome to PokéCollector!</h1>
</section>

{% endblock %}

main_app/templates/main_app/contest_confirm_delete.html
{% extends 'base.html' %}
{% block content %}
    <h1>Delete Contest</h1>
    <p>Are you sure you want to delete <span class="teal-text">{{ contest.name }}</span>?</p>
    <form action="" method="POST">
        {% csrf_token %}
        <input class="btn red" type="submit" value="CONFIRM DELETE" />
        <a href="{% url 'main:contests_index' %}" class="btn">Cancel</a>
    </form>
{% endblock %}

main_app/templates/main_app/contest_form.html
{% extends 'base.html' %}
{% block content %}
    {% if contest %}
        <h1>Edit Contest</h1>
    {% else %}
        <h1>Add Contest</h1>
    {% endif %}
    <form action="" method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Submit" class="btn" />
    </form>
    <script>
        document.addEventListener('DOMContentLoaded', function() {
            const selectElems = document.querySelectorAll('select');
            M.FormSelect.init(selectElems);

            const dateEl = document.getElementById("id_date");
            M.Datepicker.init(dateEl, {
                defaultDate: Date(),
                autoClose: true,
            });

            const labels = document.querySelectorAll("label");
            labels.forEach(label => {
                const checkbox = label.children[0];
                if (!checkbox || checkbox.getAttribute("type") !== "checkbox") return;
                checkbox.addEventListener("input", evt => {
                    if (checkbox.checked)
                        label.style.color = "teal";
                    else
                        label.style.color = "";
                });
            });
        });
    </script>
{% endblock %}

main_app/templates/main_app/pokemon_confirm_delete.html
{% extends 'base.html' %}
{% block content %}
    <h1>Delete Pokémon</h1>
    <p>Are you sure you want to delete <span class="teal-text">{{ pokemon.nickname }}</span>?</p>
    <form action="" method="POST">
        {% csrf_token %}
        <input class="btn red" type="submit" value="CONFIRM DELETE" />
        <a href="{% url 'main:pokemon_index' %}" class="btn">Cancel</a>
    </form>
{% endblock %}

main_app/templates/main_app/pokemon_form.html
{% extends 'base.html' %}
{% load main_app_extras %}
{% block content %}
    {% if pokemon %}
        <h1>Edit <span class="teal-text">{{pokemon.nickname}}</span></h1>
    {% else %}
        <h1>Add Pokémon</h1>
    {% endif %}
    <form action="" method="POST">
        {% csrf_token %}
        {% if pokemon %}
            {% with "https://www.serebii.net/art/th/"|concat:pokemon.number|concat:".png" as img_url %}
                <img id="pokemon-img" alt="pokemon image" src="{{ img_url }}"/>
            {% endwith %}
        {% else %}
            <img id="pokemon-img" alt="pokemon image" src=""/>
        {% endif %}
        <table>
            {{ form.as_table }}
        </table>
        <input type="submit" value="Submit" />
    </form>

    <script>
        const imgEl = document.getElementById("pokemon-img");
        const pokeNumEl = document.getElementById("id_number");

        pokeNumEl.addEventListener("input", evt => {
            imgEl.src = "https://www.serebii.net/art/th/" + pokeNumEl.value + ".png";
        });

    </script>
{% endblock %}

main_app/templates/main_app/training_form.html
{% extends 'base.html' %}
{% block content %}
     <form action="" method="POST">
        {{ form.as_p }}
     </form>
{% endblock %}

main_app/templates/partials/pokemon-card.html
<article class="card">
    <div class="card-content">
        <a href="{{pokemon.get_absolute_url}}">
            <h1>{{ pokemon.nickname }}</h1>
            <img alt="pokemon image" src="https://www.serebii.net/art/th/{{ pokemon.number }}.png">
        </a>

        <p><strong>lv. </strong>{{ pokemon.level }}</p>
        <ul>
            <p><strong>moves:</strong></p>
            {% for move in pokemon.moveset %}
                <li>- {{ move }}</li>
            {% endfor %}
        </ul>
    </div>

    <div class="card-action">
        <a href="{% url 'main:pokemon_update' pokemon.id %}">Edit</a>
        <a href="{% url 'main:pokemon_delete' pokemon.id %}">Delete</a>
    </div>
</article>

main_app/templates/pokemon/index.html
{% extends 'base.html' %}
{% block content %}
    <h1>My Collection</h1>
    {#  Add New Pokemon Button  #}
    <a class="btn" href="{% url 'main:pokemon_create' %}">Add Pokémon</a>

    {#  Pokemon list  #}
    <section>
    {% for pokemon in pokelist %}
    {% include 'partials/pokemon-card.html' %}
    {% endfor %}
    </section>
{% endblock %}